### PR TITLE
Hemant Kumar - Check-in Code

### PR DESCRIPTION
**Pull request by HemantNarsani37**

### CODE REVIEW

**Comment by felixshing** [comment]
Please follow this video to understand how to check-in folder with multiple files: https://www.youtube.com/watch?v=POXeHNV44_Q 

Please submit the raw data, not zip file, otherwise we cannot review and users cannot understand the inside of your code

**Comment by HemantNarsani37** [comment]
Sure. That makes sense.

I just uploaded my folder as it is! Could you please check if everything is ok?


Thanks,
Hemant
________________________________

**Comment by felixshing** [comment]
It looks good, but please write the introduction and purpose of your code in readme to give readers an understanding of your code. BTW, please make a proper name for your folder that could reflect the purpose of your code

**Comment by HemantNarsani37** [comment]
Sure. Just did that. Thanks for the guidance.

Please check if everything is ok now and do let me know.


Thanks      
________________________________

**Comment by felixshing** [comment]
Cool. Thanks!

This PR has passed review.

**Comment by HemantNarsani37** [comment]
So, just do I have to do any further any action? Or thats all? Can I not see my files in the main CoMiC now?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by HemantNarsani37** [comment]
Hey, could you please confirm if any other action is needed for the check-in?
________________________________

**Comment by comic-xr** [comment]
No further change is needed

**Pull request merged**
