### PR TITLE
To add a co author

### PR DESCRIPTION
**Pull request by pravallikamannuru321**

### CODE REVIEW

**Comment by felixshing** [comment]
You did not successfully add the co-author

**Comment by pravallikamannuru321** [comment]
I tried to add the co-author I even sent a push for it but it wasn’t
accepted. Moreover, my teammate is busy with his graduation. So please let
me know is there any other way I can add co-author.

**Comment by felixshing** [comment]
Did you follow the instructions?  The instructions can be found here: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors If you use Github desktop to commit the code, it will be easier and the instructions can be found here: https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/committing-and-reviewing-changes-to-your-project-in-github-desktop#write-a-commit-message-and-push-your-changes
 
If you do this, what errors/messages you met?

**Comment by pravallikamannuru321** [comment]
I will try this again and let you know.

**Comment by pravallikamannuru321** [comment]
Hi,
Can you please check it now. I think i became a co-author.

**Pull request merged**
