### PR TITLE
Group2_3D_Reconstruction_GMU

### PR DESCRIPTION
**Pull request by harishk19**

### CODE REVIEW

**Comment by felixshing** [comment]
In your master folder, please exclude ``hkanukur''. Moreover, please add README.md file

**Comment by harishk19** [comment]
hello,

I have removed hkanukur folder and the README file already exists.

Thanks,
Harish

**Comment by felixshing** [comment]
Okay cool. Everything looks good now. I will merge your code to main branch later. Thanks!

**Comment by harishk19** [comment]
Awesome, thanks!

**Comment by felixshing** [comment]
This PR has passed review.

**Pull request merged**
